# Generated by Django 3.0.6 on 2020-05-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_setor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='dado',
        ),
    ]
